spring:
  application:
    name: config-server
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: https://github.com/khoffy/mcommerce-config-repo.git
server:
  port: 9101